language: cpp

compiler:
  - gcc

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq g++-4.8
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
  - cd install
  - chmod +x ./install-bison-flex-c++.sh
  - sudo ./install-bison-flex-c++.sh
  - cd ..
  
script:
  - cd src/parse
  - flexc++ lexer
  - bisonc++ grammar
  - cd ../..
  - mkdir bin
  - g++ -std=c++11 src/main.cpp src/parse/lex.cc src/parse/parse.cc -o bin/compiler
  - ls -lR
