language: cpp

compiler:
  - gcc
  - clang

before_install:
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - if [ "$CXX" == "clang++" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi
  - sudo apt-get update -qq

install:
  - if [ "$CXX" == "g++" ]; then sudo apt-get install -qq g++-4.9; fi
  - if [ "$CXX" == "g++" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 90; fi
  - if [ "$CXX" == "clang++" ]; then sudo apt-get install --allow-unauthenticated -qq clang-3.5; fi
  - if [ "$CXX" == "clang++" ]; then sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-3.5 90; fi
  - if [ "$CXX" == "clang++" ]; then sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-3.5 90; fi
  - cd install
  - chmod +x ./install-bison-flex-c++.sh
  - sudo -E ./install-bison-flex-c++.sh
  - cd ..
  
script:
  - cd src/parse
  - flexc++ lexer
  - bisonc++ grammar
  - cd ../..
  - mkdir build
  - cd build
  - cmake ..
  - cmake ..
  - make
  - cd ..
  - ls -lR
