language: cpp

compiler:
  - gcc

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq g++-4.8
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
  - chmod +x ./install-bison-flex-c++.sh
  - sudo ./install-bison-flex-c++.sh
  
script:
  - flexc++ parse/lexer
  - bisonc++ parse/grammar
  - ls -lR
